- name: Fedora
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/fedora/docker.yml
  tags:
    - docker
    - fedora
 
- name: Ubuntu
  hosts: localhost
  become: true
  vars:
    ubuntu_codename: "{{ ansible_distribution_release | lower }}"
  tasks:
    - include_tasks: tasks/ubuntu/docker.yml
  tags:
    - ubuntu
