---
- name: OS
  hosts: localhost
  tasks:
    - debug:
        msg: "{{ ansible_system }}"
- name: SSH
  hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - name: Ensure .ssh directory exists
      file:
        dest: "{{ dest_key | dirname }}"
        mode: 0700
        state: directory
      tags:
        - dotfiles
        - ssh
    - name: Install ssh key
      ignore_errors: true
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600
      tags:
        - ssh
    - name: Install ssh key public
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: 0644
      tags:
        - ssh
    - name: Set authorized key took from file
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        key: "{{ lookup('file', item) }}"
        state: present
      with_fileglob:
        - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
      tags:
        - dotfiles
        - ssh

- name : Neovim
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/multi-platform/neovim.yml

- name: Run tasks
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/homebrew.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/watchers.yml

- name: DOTFILES
  hosts: localhost
  tasks:
    - include_tasks: tasks/dotfiles.yml
  tags:
    - dotfiles


- name: Debian
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/debian/ripgrep.yml
  tags:
    - debian
    - shortcuts

- name: Ubuntu
  hosts: localhost
  tasks:
    - include_tasks: tasks/ubuntu/ripgrep.yml
    - include_tasks: tasks/ubuntu/forge.yml
    - include_tasks: tasks/ubuntu/docker.yml
  tags:
    - ubuntu
    - shortcuts


- name: Macos
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/macos/global.yml
  tags:
    - macos
    - shortcuts

- name: Arch
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/arch/virtualbox.yml
  tags:
    - arch
    - virtualbox
    - vagrant

- name: Arch-Software
  hosts: localhost
  become: true
  vars:
    packages:
      - pamixer
      - feh
      - hyprland
      - waybar
      - dolphin
      - wofi
      - rofi
      - polybar
  tasks:
    - include_tasks: tasks/arch/packages.yml
  tags:
    - arch

    #- name: Arch-Software
    #  hosts: localhost
    #  become: true
    #  vars:
    #    url: "https://aur.archlinux.org"
    #    dest_dir: "{{ lookup('env', 'HOME') }}/tmp"
    #    packages:
    #      - "zoom"
    #      - "slack-desktop"
    #      - "gitkraken"
    #      - "xmind" 
    #      - "datagrip"
    #      - "postman-bin"
    #  tasks:
    #    - include_tasks: tasks/arch/from-aur-repo.yml
    #  tags:
    #    - arch
    #    - aur  

