---
- name: SSH
  hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - name: Ensure .ssh directory exists
      file:
        dest: "{{ dest_key | dirname }}"
        mode: 0700
        state: directory
      tags:
        - dotfile
        - ssh
    - name: Install ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600
      tags:
        - dotfile
        - ssh
    - name: Install ssh key public
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: 0644
      tags:
        - dotfile
        - ssh
    - name: Set authorized key took from file
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        key: "{{ lookup('file', item) }}"
        state: present
      with_fileglob:
        - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
      tags:
        - dotfile
        - ssh

- name: MAC
  hosts: localhost
  tasks:
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/homebrew.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/dotfiles.yml

