- name: Use Kitty
  hosts: localhost
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
  tasks:
    - include_tasks: tasks/ubuntu/kitty.yml

- name: GNOME Hotkeys
  hosts: localhost
  tags:
    - keymappings
  tasks:
    - include_tasks: tasks/ubuntu/keyboard-mappings.yml

- name : Neovim
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/multi-platform/neovim.yml

- name : Packages
  hosts: localhost
  tasks:
    - package:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - gnome-tweaks

- name: Install NPM/Node
  hosts: localhost
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    nvm_version: "v0.40.3"
  tasks:
    - include_tasks: tasks/ubuntu/node.yml


- name: Install SDKMAN and Java
  hosts: localhost
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    java_version: "21-graalce"
  tasks:
    - include_tasks: tasks/ubuntu/java.yml


- name: Install Golang
  hosts: localhost
  become: true
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    go_version: "1.25.1"
  tasks:
    - include_tasks: tasks/ubuntu/golang.yml

- name: Link Unreal
  hosts: localhost
  tags:
    - unreal
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    unreal_engine_path: "/home/{{ ansible_user_id }}/UnrealEngineBin"
    desktop_file_name: "unreal-editor.desktop"
    applications_dir: "/home/{{ ansible_user_id }}/.local/share/applications"
  tasks:
    - include_tasks: tasks/ubuntu/unreal.yml
  handlers:
    - name: Reload desktop database
      command: update-desktop-database
      listen: "Reload desktop database"
      become: yes

