- name: GNOME Hotkeys
  hosts: localhost
  tasks:
    - include_tasks: tasks/ubuntu/keyboard-mappings.yml

- name : Neovim
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/multi-platform/neovim.yml

- name : Packages
  hosts: localhost
  tasks:
    - package:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - gnome-tweaks

- name: Install NPM/Node
  hosts: localhost
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    nvm_version: "v0.40.3"
  tasks:
    - include_tasks: tasks/ubuntu/node.yml


- name: Install SDKMAN and Java
  hosts: localhost
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    java_version: "21-graalce"
  tasks:
    - include_tasks: tasks/ubuntu/java.yml


- name: Install Golang
  hosts: localhost
  become: true
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    go_version: "1.25.1"
  tasks:
    - include_tasks: tasks/ubuntu/golang.yml
