- name: Use Kitty
  hosts: localhost
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
  tasks:
    - include_tasks: tasks/ubuntu/kitty.yml

- name: Kensington Blade Remapping
  hosts: localhost
  tags:
    - kensington
  vars:
    script_name: swap-kensinton-mouse-buttons.sh
    script_path: "{{ ansible_env.HOME }}/{{ script_name }}"
    autostart_dir: "{{ ansible_env.HOME }}/.config/autostart"
  tasks:
    - include_tasks: tasks/ubuntu/kensinton-blade.yml

- name: GNOME Mouse Handedness Toggle
  hosts: localhost
  tags:
    - keymappings
    - mouse
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    script_path: "{{ ansible_user_dir }}/.local/bin/toggle-mouse-handedness.sh"
    shortcut_binding: "<Alt>m"
    shortcut_name: "Toggle Mouse Handedness"
    new_keybinding_path: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/"
  tasks:
    - include_tasks: tasks/ubuntu/main-mouse-button-toggle.yml

- name: GNOME Hotkeys
  hosts: localhost
  tags:
    - keymappings
  tasks:
    - include_tasks: tasks/ubuntu/keymappings.yml

- name: GNOME Forge Extension
  hosts: localhost
  tags:
    - popos
    - gnome
    - forge
  tasks:
    - include_tasks: tasks/ubuntu/forge.yml

- name : Neovim
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/multi-platform/neovim.yml

- name : Packages
  hosts: localhost
  tasks:
    - package:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - gnome-tweaks
        - clangd
        - tmux

- name: Install NPM/Node
  hosts: localhost
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    nvm_version: "v0.40.3"
  tasks:
    - include_tasks: tasks/ubuntu/node.yml


- name: Install SDKMAN and Java
  hosts: localhost
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    java_version: "21-graalce"
  tasks:
    - include_tasks: tasks/ubuntu/java.yml


- name: Install Golang
  hosts: localhost
  become: true
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    go_version: "1.25.1"
  tasks:
    - include_tasks: tasks/ubuntu/golang.yml

- name: Install KVM and Vagrant
  hosts: localhost
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
  tasks:
    - include_tasks: tasks/ubuntu/kvm-vagrant.yml

- name: Link Unreal
  hosts: localhost
  tags:
    - unreal
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    unreal_engine_path: "/home/{{ ansible_user_id }}/UnrealEngineBin"
    desktop_file_name: "unreal-editor.desktop"
    applications_dir: "/home/{{ ansible_user_id }}/.local/share/applications"
  tasks:
    - include_tasks: tasks/ubuntu/unreal.yml
  handlers:
    - name: Reload desktop database
      command: update-desktop-database
      listen: "Reload desktop database"
      become: yes

