- name: Remove folder
  file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles"
    state: absent
- name: Cloning dotfiles
  git:
    repo: "git@github.com:Jairanpo/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags: 
    - install
    - dotfiles
- name: Make scripts executable
  file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles/{{ item }}"
    mode: u+x
  with_items:
    - macos
    - linux
    - install
- name: Stow dotfiles MacOs
  shell: "cd {{ lookup('env', 'HOME') }}/.dotfiles && ./macos"
  tags: 
    - install
    - macos
    - dotfiles
  when: "'Darwin' in ansible_system"
- name: Stow dotfiles for linux
  shell: "cd {{ lookup('env', 'HOME') }}/.dotfiles && ./linux"
  tags: 
    - install
    - linux
    - dotfiles
  when: "'Linux' in ansible_system"
- name: Source .zshrc
  shell: "cd {{ lookup('env', 'HOME') }}/.zshrc"
  ignore_errors: yes

