- homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
  when: "'darwin' in ansible_system"
  with_items:
    - git
    - fzf
    - stow
    - make
    - tmux
    - nvim
    - black
    - python3
