- package:
    name: "{{ item }}"
    state: present
  when: "'Linux' in ansible_system"
  become: true
  with_items:
    - git
    - fzf
    - stow
    - make
    - tmux
    - i3
    - neovim
    - direnv
