- name: Install Zsh
  become: true
  package:
    name: zsh
    state: present
- name: Git checkout
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
