- name: Install Zsh Mac
  package:
    name: zsh
    state: present
  when: "'Darwin' in ansible_system"
- name: Install Zsh Linux
  become: true
  package:
    name: zsh
    state: present
  when: "'Linux' in ansible_system"
- name: Checkout Powerlevel10k
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
