---
- name: Task to run on Fedora
  when: "'Debian' in ansible_distribution"
  block:
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable"
        state: present
    - name: Update apt and install docker cd
      package:
        name: docker-ce
        state: latest
        update_cache: true

