- name: Ensure the scripts directory exists
  file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: '0755'

- name: Deploy the toggle script
  copy:
    content: |
      #!/bin/bash
      current=$(dconf read /org/gnome/desktop/peripherals/mouse/left-handed)
      if [[ "$current" == "true" ]]; then
        dconf write /org/gnome/desktop/peripherals/mouse/left-handed false
      else
        dconf write /org/gnome/desktop/peripherals/mouse/left-handed true
      fi
    dest: "{{ script_path }}"
    mode: '0755'

- name: Define the custom keybinding's command and name
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "{{ new_keybinding_path }}command", value: "'{{ script_path }}'" }
    - { key: "{{ new_keybinding_path }}name", value: "'{{ shortcut_name }}'" }
    - { key: "{{ new_keybinding_path }}binding", value: "'{{ shortcut_binding }}'" }


